# .buildkite/pipeline.device.yml
steps:
- label: Flash Unit
  concurrency: 1
  concurrency_group: "link-iot-server"
  agents:
    # Target an agent which has been started like:
    # buildkite-agent start --tags cartlink=cartlink-1
    cartlink: $CARTLINK
  command: .buildkite/device.sh $DEVICE
