steps:
  - label: Select Cartlink
    timeout_in_minutes: 10
    concurrency: 1
    concurrency_group: "link-iot-server"
    timeout_in_minutes: 10
    agents:
      queue: raspberrypi
    command:
      - "/home/pi/.buildkite-agent/builds/raspberrypi-1/techwing/cartlink-flash/.buildkite/build.sh"

  - block: "Select CartLink"
    fields:
      - select: "Stream"
        key: "cartlink"
        options:
          - label: "Cartlink-1"
            value: "cartlink-1"
          - label: "Cartlink-2"
            value: "cartlink-2"
          - label: "Cartlink-3"
            value: "cartlink-3"
          - label: "Cartlink-4"
            value: "cartlink-4"
          - label: "Cartlink-5"
            value: "cartlink-5"
          - label: "Cartlink-6"
            value: "cartlink-6"

  - block: "Select Device"
    fields:
      - select: "Stream"
        key: "device"
        options:
          - label: "Linaro"
            value: "linaro"
          - label: "Android"
            value: "android"
            
  - block: "Deploy To"
    fields:
      - select: "Regions"
        key: "deploy-regions"
        hint: "Which regions should we deploy this to? :earth_asia:"
        multiple: true
        default:
          - "na"
          - "eur"
          - "asia"
          - "aunz"
        options:
          - label: "North America"
            value: "na"
          - label: "Europe"
            value: "eur"
          - label: "Asia"
            value: "asia"
          - label: "Oceania"
            value: "aunz"
