steps:
  - block: "Select CartLink"
    fields:
      - select: "Cart-Link"
        key: "cartlink"
        hint: "Select Cartlink to flash."
        required: true
        options:
          - label: "Cartlink-1"
            value: "cartlink-1"
          - label: "Cartlink-2"
            value: "cartlink-2"
          - label: "Cartlink-3"
            value: "cartlink-3"
          - label: "Cartlink-4"
            value: "cartlink-4"
          - label: "Cartlink-5"
            value: "cartlink-5"
          - label: "Cartlink-6"
            value: "cartlink-6"
          - label: "Cartlink-7"
            value: "cartlink-7"
          - label: "Cartlink-8"
            value: "cartlink-8"
          - label: "Cartlink-9"
            value: "cartlink-9"
          - label: "Cartlink-10"
            value: "cartlink-10"
    
  - block: ":closed_lock_with_key: CartLink"
    prompt: ":warning:Please select the unit to flash:warning:"  
    
  - block: "Select Uint"
    fields:
      - select: "Device"
        key: "device"
        hint: "Select Device to flash."
        multiple: true
        options:
          - label: "ADL"
            value: "adl"
          - label: "ADR"
            value: "adr"
          - label: "Maint"
            value: "maint"
          - label: "Tablet"
            value: "tablet"
   
  - label: Update Agent
    concurrency: 1
    concurrency_group: "link-iot-server"
    agents:
       cartlink=cartlink-1
    command: echo $(buildkite-agent meta-data get cartlink)
    command: echo $BUILDKITE_BUILD_CHECKOUT_PATH
    command: echo $BUILDKITE_BIN_PATH
    
  - label: ":pipeline:"
    command: |
       echo "sample"
       # Grab the meta-data from the block step above and make it available
       # within the next pipeline upload command
       #
       # Note the double dollars which escapes to one dollar during the pipeline
       # upload so that the substitution will work later when it is run
       export CARTLINK="$$(buildkite-agent meta-data get cartlink)"
       export DEVICE="$$(buildkite-agent meta-data get device)"
       /home/pi/.buildkite-agent/bin/buildkite-agent pipeline upload $BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/pipeline.device.yml
        
