# .buildkite/pipeline.device.yml
steps:
  - label: Flash Unit
    concurrency: 1
    concurrency_group: "cartlink-server"
    agents:
      # Target an agent which has been started like:
      # buildkite-agent start --tags cartlink=raspi-hostname
      cartlink: $CARTLINK
    command: python $BUILDKITE_BUILD_CHECKOUT_PATH/raspi_flash.py $DEVICE
