steps:
  - block: "Select CartLink"
    fields:
      - select: "Cart-Link"
        key: "cartlink"
        hint: "Select Cartlink to flash."
        options:
          - label: "cartlink-aa-000001"
            value: "cartlink-aa-000001"
          - label: "cartlink-aa-000002"
            value: "cartlink-aa-000002"
          - label: "cartlink-aa-000003"
            value: "cartlink-aa-000003"
          - label: "cartlink-aa-000004"
            value: "cartlink-aa-000004"
          - label: "cartlink-aa-000005"
            value: "cartlink-aa-000005"
          - label: "cartlink-aa-000006"
            value: "cartlink-aa-000006"
          - label: "cartlink-aa-000007"
            value: "cartlink-aa-000007"
          - label: "cartlink-aa-000008"
            value: "cartlink-aa-000008"

  - block: ":closed_lock_with_key: CartLink"
    prompt: ":warning: Please make sure you selected the cart link to flash the unit :warning:"

  - block: "Select Unit"
    fields:
      - select: "Unit"
        key: "device"
        hint: "Select Device to flash."
        options:
          - label: "ADL"
            value: "adl"
          - label: "ADR"
            value: "adr"
          - label: "Maint"
            value: "maint"
          - label: "Tablet"
            value: "tablet"

  - label: ":pipeline:"
    command: |
       export CARTLINK="$$(buildkite-agent meta-data get cartlink)"
       export DEVICE="$$(buildkite-agent meta-data get device)"
       buildkite-agent pipeline upload $BUILDKITE_BUILD_CHECKOUT_PATH/.buildkite/pipeline.device.yml

