steps:
  - label: CartLink Flash
    timeout_in_minutes: 10
    concurrency: 1
    agents:
      queue: raspberypi
    command:
      - ".buildkite/build.sh"

  - block: "Request Release"
    fields:
      - text: "Code Name"
        key: "release-name"