steps:
  - block: "Select CartLink"
    concurrency: 1
    concurrency_group: "tests"
    fields:
      - select: "Cart-Link"
        key: "cartlink"
        hint: "Select Cartlink to flash."
        options:
          - label: "Cartlink-1"
            value: "cartlink-1"
          - label: "Cartlink-2"
            value: "cartlink-2"
          - label: "Cartlink-3"
            value: "cartlink-3"
          - label: "Cartlink-4"
            value: "cartlink-4"
          - label: "Cartlink-5"
            value: "cartlink-5"
          - label: "Cartlink-6"
            value: "cartlink-6"
    
  - wait
  
  - block: ":closed_lock_with_key: CartLink"
    prompt: ":warning:Please select the unit to flash:warning:"  
    
  - wait
  
  - block: "Select Device"
    concurrency: 1
    concurrency_group: "tests"
    fields:
      - select: "Device"
        key: "device"
        hint: "Select Device to flash."
        options:
          - label: "ADL"
            value: "adl"
          - label: "ADR"
            value: "adr"
          - label: "Maint"
            value: "maint"
          - label: "Tablet"
            value: "tablet"
            
  - label: Select Cartlink
    command: "/home/pi/buildkite/.buildkite/build.sh"

  - block: "Request Release"
    fields:
      - text: "cartlink Name"
        key: "release-name"
       
  - label: Select Cartlink
    command: "echo release-name"
