# .buildkite/pipeline.device.yml
steps:
  - label: Install Requirements
    concurrency: 1
    concurrency_group: "cartlink-server"
    agents:
      cartlink: $CARTLINK
    command: sudo chmod 755 $BUILDKITE_BUILD_CHECKOUT_PATH/raspi_flash_requirements.sh && /bin/bash $BUILDKITE_BUILD_CHECKOUT_PATH/raspi_flash_requirements.sh && export JSON_FILE_PATH=$BUILDKITE_BUILD_CHECKOUT_PATH

  - label: Flash Unit
    concurrency: 1
    concurrency_group: "cartlink-server"
    agents:
      # Target an agent which has been started like:
      # buildkite-agent start --tags cartlink=raspi-hostname
      cartlink: $CARTLINK
    command: python $BUILDKITE_BUILD_CHECKOUT_PATH/raspi_flash.py $DEVICE
