steps:
  - label: Select Cartlink
    command: "/home/pi/buildkite/.buildkite/build.sh"

  - block: "Select CartLink"
    fields:
      - select: "Cart-Link"
        key: "cartlink"
        hint: "Select Cartlink to flash."
        options:
          - label: "Cartlink-1"
            value: "cartlink-1"
          - label: "Cartlink-2"
            value: "cartlink-2"
          - label: "Cartlink-3"
            value: "cartlink-3"
          - label: "Cartlink-4"
            value: "cartlink-4"
          - label: "Cartlink-5"
            value: "cartlink-5"
          - label: "Cartlink-6"
            value: "cartlink-6"
            
  - label: Select Cartlink
    command: "echo $cartlink"
    
  - block: "Select Device"
    fields:
      - select: "Device"
        key: "device"
        hint: "Select Device to flash."
        options:
          - label: "Linaro"
            value: "linaro"
          - label: "Android"
            value: "android"

  - block: "Request Release"
    fields:
      - text: "cartlink Name"
        key: "release-name"
