steps:
  - label: CartLink Flash
    timeout_in_minutes: 10
    agents:
      queue: raspberypi
    command:
      - "/home/pi/.buildkite-agent/builds/raspberrypi-1/techwing/cartlink-flash/.buildkite/build.sh"

  - block: "Request Release"
    fields:
      - text: "Code Name"
        key: "release-name"